title: "Yadel Lopez"
description: "Software Engineer and Distributed Systems Architect with 15+ years designing fault-tolerant, multi-tenant cloud-native solutions. Proven leadership in observability-first practices, platform resiliency, and delivering multimillion-dollar impact."
theme: jekyll-theme-cayman
author: "Yadel Lopez"
avatar: "assets/images/profile.jpg"
linkedin_username: dotnetspark
github_username: dotnetspark
email: yadel.lopez@eblsoftware.com
location: "Naples, FL"
phone: "(239) 378-3633"
